apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: ticketing
build:
  artifacts:
    - image: iuliancarnaru/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
manifests:
  rawYaml:
    - infra/k8s/auth-depl.yaml
    - infra/k8s/auth-mongo-depl.yaml
    - infra/k8s/ingress-srv.yaml
