apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: ticketing
build:
  artifacts:
    - image: iuliancarnaru/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    - image: iuliancarnaru/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    - image: iuliancarnaru/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    - image: iuliancarnaru/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: iuliancarnaru/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: iuliancarnaru/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: '**/*.js'
manifests:
  rawYaml:
    - infra/k8s/auth-depl.yaml
    - infra/k8s/client-depl.yaml
    - infra/k8s/tickets-depl.yaml
    - infra/k8s/orders-depl.yaml
    - infra/k8s/nats-depl.yaml
    - infra/k8s/expiration-depl.yaml
    - infra/k8s/payments-depl.yaml
    - infra/k8s/auth-mongo-depl.yaml
    - infra/k8s/tickets-mongo-depl.yaml
    - infra/k8s/orders-mongo-depl.yaml
    - infra/k8s/payments-mongo-depl.yaml
    - infra/k8s/expiration-redis-depl.yaml
    - infra/k8s/ingress-srv.yaml
